#### 10 queries for MIMIC III database #####

--1--
SELECT subject_id, admission_type, diagnosis 
	FROM admissions 
	ORDER BY subject_id;

######################################################
--subject_id,admission_type,diagnosis
--2,NEWBORN,NEWBORN
--3,EMERGENCY,HYPOTENSION
--4,EMERGENCY,"FEVER,DEHYDRATION,FAILURE TO THRIVE"
--5,NEWBORN,NEWBORN
--6,ELECTIVE,CHRONIC RENAL FAILURE/SDA
--7,NEWBORN,NEWBORN
--8,NEWBORN,NEWBORN
--9,EMERGENCY,HEMORRHAGIC CVA
--10,NEWBORN,NEWBORN
--11,EMERGENCY,BRAIN MASS
--12,ELECTIVE,PANCREATIC CANCER/SDA
--13,EMERGENCY,CORONARY ARTERY DISEASE
--16,NEWBORN,NEWBORN
--17,EMERGENCY,PERICARDIAL EFFUSION
--17,ELECTIVE,PATIENT FORAMEN OVALE\ PATENT FORAMEN OVALE MINIMALLY INVASIVE/SDA
--18,EMERGENCY,HYPOGLYCEMIA;SEIZURES
--19,EMERGENCY,C-2 FRACTURE
--20,ELECTIVE,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT/SDA
#######################################################


--2--
SELECT DISTINCT diagnosis
	FROM admissions
	WHERE length(diagnosis) > 30;

#######################################################
--diagnosis
--"CHANGE IN MENTAL STATUS,SEIZURE"
--CORONARY ARTERY DISEASE\CATH WITH BRACHY STANDBY
--RIGHT PLEURAL EFFUSION CIRRHOSIS PHT
--"CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT, RE-DO; MITRAL VALVE REPLACEMENT VIA LEFT THORACOTOMY"
--RESPIRATORY DISTRESS;PNEUMONIA;CHRONIC OBST PULM DISEASE
--ACUTE ANTERIOR MYOCARDIAL INFARCTION
--BILATERAL CAROTID STENOSIS\RIGHT CAROTID ANGIOGRAM
--CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT WITH MVR; ? MAZE
--CORONARY ARTERY DISEASE;RECURRENT PAIN\CATH WITH BRACHY S/B
--AORTIC VALVE DISORDER\AORTIC VALVE REPLACEMENT 
--THOMACIC ANEURYSM\THORACOABDOMINAL ENDARTERECTOMY/ RIGHT PARTIAL BYPASS; LUBAR DRAIN  
--CORONARY ARTERY DISEASE;URINARY TRACT INFECTION;ELEVATED TROPONIN
--AORTIC STENOSIS\RIGHT AND LEFT HEART CATHETERIZATION
--"DIABETIC KETOACIDOSIS;CVA;FEVER,ETIOLOGY UNKNOWN"
--MITRAL REGURGITATION\MVR; ? CORONARY ARTERY BYPASS GRAFT /SDA
--RIGHT VENTRICULAR LEAD MALFUNCTION;INAPPROPRIATE IMPLANTABLE CARDIOVERTER-DEFIBRILLATOR FRING\RIGHT VENTRICULAR IMPLANTABLE CARDIOVERTER-DEFIBRILLATOR LEAD EXTRACTION/SDA
--"ASD\ATRIAL SEPTAL DEFECT REPAIR,  PATENT FORAMEN OVALE CLOSURE MINIMALLY INVASIVE /SDA"
--INTRACRANIAL HEMORRHAGE;SEIZURE;TACHYCARDIA
--ACUTE RENAL FAILURE-PELVIC MASS
#######################################################

--3--
SELECT subject_id, drug_type, drug, route
	FROM prescriptions
	WHERE drug 
	LIKE 'n%';

#######################################################
--subject_id,drug_type,drug,route
--91314,MAIN,neutr,PO
--10144,MAIN,nifer,ORAL
--5181,MAIN,nifed,ORAL
--99085,MAIN,naratriptan,ORAL
--2369,MAIN,naltrexone,ORAL
--5940,MAIN,nutra,TP
--8461,MAIN,nif,PO
--7985,MAIN,nexium,PO
--18255,MAIN,nifed,PO
--13841,MAIN,nifedipine,ORAL
--17406,MAIN,nifed,ORAL
--28291,MAIN,nap,OU
--22782,MAIN,neutr,PO
--54739,MAIN,neut,NG
--45160,MAIN,nia,PO
--50141,MAIN,neoral,PO
--50141,MAIN,neoral,PO
--55689,MAIN,nepafenac,OD
--28866,MAIN,nystat,PO/NG
#######################################################

--4--
SELECT drug_type, COUNT(*)
	FROM PRESCRIPTIONS
	GROUP BY drug_type;

#######################################################
--drug_type,count
--ADDITIVE,14479
--BASE,925089
--MAIN,3216882
#######################################################

--5--
SELECT admission_type, diagnosis, COUNT(*)
	FROM admissions
	GROUP BY admission_type, diagnosis;

#######################################################
--admission_type,diagnosis,count
--EMERGENCY,PULMONARY EMBOLIS; SEPSIS,1
--URGENT,CARDIAC TAMPONADE,1
--EMERGENCY,RESPIRATORY FAILURE;RULE-OUT MYOCARDIAL INFARCTION,1
--EMERGENCY,HEPATIC BLEED,2
--EMERGENCY,ACUTE CORONARY STENT THROMBOSIS,1
--EMERGENCY,SUICIDAL IDEATION;FOREIGN BODY INGESTION,1
--ELECTIVE,SPLENOMEGALY/HYPERTENSION/SDA,1
--EMERGENCY,SIGMOID CANCER,1
--EMERGENCY,COLONIC MASS,2
--EMERGENCY,PULMOMNARY EMBOLUS,1
--EMERGENCY,GASTRO INTESTINAL BLEEDING,1
--EMERGENCY,MOTOR VEHICLE COLLISON;? SEIZURES,1
--EMERGENCY,CARDIAC CATHERIZATION,1
--EMERGENCY,ATHEROSCLEROSIS W/ GANGRENE,1
--EMERGENCY,BILATERAL CEREBELLAR STROKE,1
--ELECTIVE,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT; W/LIMA RIMA ? LRA/SDA,1
--ELECTIVE,"MITRAL STENOSIS\MITRAL VALVE REPAIR, ? REPLACEMENT ",1
--EMERGENCY,CONGESTIVE HEART FAILURE;CHRONIC OBST PULM DISEASE;TELEMETRY,1
--EMERGENCY,DELTA MS,3
#######################################################

--6--
SELECT DISTINCT subject_id, hadm_id, drg_type, description
	FROM drgcodes
	WHERE drg_type != 'HCFA'
	ORDER BY hadm_id;

#######################################################
--subject_id,hadm_id,drg_type,description
--58526,100001,APR ,Diabetes
--58526,100001,MS,DIABETES W CC
--54610,100003,APR ,Peptic Ulcer & Gastritis
--54610,100003,MS,G.I. HEMORRHAGE W CC
--23018,100007,APR ,Major Small & Large Bowel Procedures
--533,100009,APR ,Coronary Bypass w/o Cardiac Cath Or Percutaneous Cardiac Procedure
--533,100009,MS,CORONARY BYPASS W/O CARDIAC CATH W/O MCC
--55853,100010,APR ,Kidney & Urinary Tract Procedures for Malignancy
--55853,100010,MS,KIDNEY & URETER PROCEDURES FOR NEOPLASM W CC
--87977,100011,APR ,Tracheostomy W Long Term Mechanical Ventilation W Extensive Procedure
--87977,100011,MS,"ECMO OR TRACH W MV 96+ HRS OR PDX EXC FACE, MOUTH & NECK W MAJ O.R."
--60039,100012,APR ,Coronary Bypass w/o Cardiac Cath Or Percutaneous Cardiac Procedure
--60039,100012,MS,CORONARY BYPASS W/O CARDIAC CATH W/O MCC
--23804,100014,APR ,"Shoulder, Upper Arm & Forearm Procedures"
--23804,100014,MS,"SHOULDER,ELBOW OR FOREARM PROC,EXC MAJOR JOINT PROC W/O CC/MCC"
--68591,100016,APR ,Tracheostomy W Long Term Mechanical Ventilation W/O Extensive Procedure
--68591,100016,MS,"TRACH W MV 96+ HRS OR PDX EXC FACE, MOUTH & NECK W/O MAJ O.R."
#######################################################

--7--
SELECT ad.diagnosis, dr.drg_code, dr.description
	FROM admissions ad
	INNER JOIN drgcodes dr
	ON ad.hadm_id = dr.hadm_id;

#######################################################
--diagnosis,drg_code,description
--NEWBORN,390,NEONATE WITH OTHER SIGNIFICANT PROBLEMS
--NEWBORN,385,"NEONATES, DIED OR TRANSFERRED TO ANOTHER ACUTE CARE FACILITY"
--PNEUMONIA-FEVER-POST-OP,101,"OTHER RESPIRATORY SYSTEM DIAGNOSES WITH COMPLICATIONS, COMORBIDITIES"
--CONGESTIVE HEART FAILURE;?R/O MI,107,CORONARY BYPASS WITH CARDIAC CATHETER
--LEFT CVA,014,SPECIFIC CEREBROVASCULAR DISORDERS EXCEPT TRANSIENT ISCHEMIC ATTACK
--CONGESTIVE HEART FAILURE EXACERBATION,078,PULMONARY EMBOLISM
--TRAUM,483,"TRACHEOSTOMY EXCEPT FOR FACE, MOUTH, & NECK DIAGNOSES"
--PERFORATED VISCUS,202,CIRRHOSIS & ALCOHOLIC HEPATITIS
--V-FIB ARREST,514,CARDIAC DEFIBRILLATOR IMPLANT WITH CARDIAC CATHETERIZATION
--R/O CVA,014,SPECIFIC CEREBROVASCULAR DISORDERS EXCEPT TRANSIENT ISCHEMIC ATTACK
--HYPERTENSION,416,SEPTICEMIA AGE >17
--SDH,028,"TRAUMATIC STUPOR & COMA, COMA <1 HR AGE >17 WITH COMPLICATIONS, COMORBIDITIES"
--+ETT\CATH,107,CORONARY BYPASS WITH CARDIAC CATHETER
--CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS GRAFT/SDA,109,CORONARY BYPASS WITHOUT CARDIAC CATHETER
--UNSTABLE ANGINA\CATH,107,CORONARY BYPASS WITH CARDIAC CATHETER
--FEVER; MS FLARE,475,RESPIRATORY SYSTEM DIAGNOSIS WITH VENTILATOR SUPPORT
--BRAIN ANEURYSM,131,"PERIPHERAL VASCULAR DISORDERS WITHOUT COMPLICATIONS, COMORBIDITIES"
--CORONARY ARTERY DISEASE,109,CORONARY BYPASS WITHOUT CARDIAC CATHETER
--S/P MVA,485,"LIMB REATTACHMENT, HIP AND FEMUR PROCEDURE FOR MULTIPLE SIGNIFICANT TRAUMA"
#######################################################

--8--
SELECT ad.admission_type, ad.diagnosis, SUBSTR(ip.ordercategoryname, 1, 10)
	FROM INPUTEVENTS_MV ip
	INNER JOIN admissions ad
	ON ip.hadm_id = ad.hadm_id
	ORDER BY ip.ordercategoryname;

#######################################################
--admission_type,diagnosis,substr
--EMERGENCY,ASTHMA;COPD EXACERBATION,01-Drips
--EMERGENCY,ASTHMA;COPD EXACERBATION,01-Drips
--EMERGENCY,ASTHMA;COPD EXACERBATION,01-Drips
--EMERGENCY,INTRAPARENCHYMAL HEMORRHAGE,01-Drips
--EMERGENCY,INTRAPARENCHYMAL HEMORRHAGE,01-Drips
--ELECTIVE,?STERNAL ISSUES\STERNUM REVISION ? PLATING/SDA,01-Drips
--ELECTIVE,?STERNAL ISSUES\STERNUM REVISION ? PLATING/SDA,01-Drips
--EMERGENCY,CHOLELITHIASIS,01-Drips
--EMERGENCY,CHOLELITHIASIS,01-Drips
--ELECTIVE,?STERNAL ISSUES\STERNUM REVISION ? PLATING/SDA,01-Drips
--EMERGENCY,CORONARY ARTERY DISEASE;CARDIOGENIC SHOCK\LEFT ANTERIOR DESCENDING ARTERY; ANGIOPLASTY/STENT,01-Drips
--EMERGENCY,FEVER;NAUSEA;ABDOMINAL PAIN,01-Drips
--EMERGENCY,FEVER;NAUSEA;ABDOMINAL PAIN,01-Drips
--EMERGENCY,ST ELEVATED MYOCARDIAL INFARCTION,01-Drips
--EMERGENCY,TRAUMA,01-Drips
--EMERGENCY,FEVER;NAUSEA;ABDOMINAL PAIN,01-Drips
--EMERGENCY,FEVER;NAUSEA;ABDOMINAL PAIN,01-Drips
--EMERGENCY,FEVER;NAUSEA;ABDOMINAL PAIN,01-Drips
--EMERGENCY,FEVER;NAUSEA;ABDOMINAL PAIN,01-Drips
#######################################################

--9--
SELECT ic.first_careunit, pr.drug, COUNT(pr.drug), AVG(ic.los)
	FROM ICUSTAYS ic
	INNER JOIN PRESCRIPTIONS pr
	ON ic.subject_id = pr.subject_id
	GROUP BY ic.first_careunit, pr.drug;

#######################################################
--first_careunit,drug,count,avg
--CCU,0.45 % Sodium Chloride,6,4.5754
--CCU,0.45% Sodium Chloride,573,3.43353071553228
--CCU,0.83% Sodium Chloride,89,4.81801460674157
--CCU,0.9% Sodium Chloride,22848,5.27756944590339
--CCU,0.9% Sodium Chloride (EXCEL BAG),12,4.683
--CCU,0.9% Sodium Chloride (Mini Bag Plus),3229,5.96394747599876
--CCU,1,1,31.4416
--CCU,1/2 NS,3398,3.82343746321366
--CCU,1/4 NS,13,7.74241538461538
--CCU,23.4% Sodium Chloride,1,3.0145
--CCU,300 mcg Vial,8,3.517675
--CCU,5% Dextrose,19045,6.13175850879499
--CCU,5% Dextrose (EXCEL BAG),1175,6.46500570212766
--CCU,5 Syringes (NS),8,4.6704625
--CCU,Abacavir,1,0.8741
--CCU,Abacavir Sulfate,49,3.97530816326531
--CCU,Abciximab,86,4.02266627906977
--CCU,Abilify,2,3.4636
--CCU,abiraterone (Zytiga),1,4.9333
#######################################################

--10--
SELECT DISTINCT ad.hadm_id, ad.diagnosis, mb.spec_type_desc
	FROM admissions ad
	INNER JOIN microbiologyevents mb
	ON ad.hadm_id = mb.hadm_id;

#######################################################
--hadm_id,diagnosis,spec_type_desc
--100001,DIABETIC KETOACIDOSIS,BLOOD CULTURE
--100001,DIABETIC KETOACIDOSIS,MRSA SCREEN
--100001,DIABETIC KETOACIDOSIS,STOOL
--100001,DIABETIC KETOACIDOSIS,URINE
--100003,UPPER GI BLEED,BLOOD CULTURE
--100003,UPPER GI BLEED,MRSA SCREEN
--100003,UPPER GI BLEED,SEROLOGY/BLOOD
--100003,UPPER GI BLEED,URINE
--100006,COPD FLARE,SPUTUM
--100006,COPD FLARE,SWAB
--100007,BOWEL OBSTRUCTION,BLOOD CULTURE
--100007,BOWEL OBSTRUCTION,SPUTUM
--100007,BOWEL OBSTRUCTION,STOOL
--100007,BOWEL OBSTRUCTION,URINE
--100009,CORONARY ARTERY DISEASE,MRSA SCREEN
--100009,CORONARY ARTERY DISEASE,Staph aureus Screen
--100009,CORONARY ARTERY DISEASE,URINE
--100011,MOTOR VEHICLE ACCIDENT WITH UNSPECIFIED INJURIES,BLOOD CULTURE
--100011,MOTOR VEHICLE ACCIDENT WITH UNSPECIFIED INJURIES,BRONCHOALVEOLAR LAVAGE
--100011,MOTOR VEHICLE ACCIDENT WITH UNSPECIFIED INJURIES,MRSA SCREEN
#######################################################